//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("4.3.0")]
[assembly: AssemblyFileVersion("4.3.0")]
[assembly: AssemblyInformationalVersion("4.3.0-beta.1+2.Branch.releases/4.3.0.Sha.08394159f3fc857dd42af9e556ff8abd8e76910d")]

